# -*- coding: utf-8 -*-


{   'active': False,
    'author': u'Ingenieria Adhoc',
    'category': 'base.module_category_hidden',
    'demo_xml': [],
    'depends': [u'product'],
    'description': u'Kinesis Athletics',
    'init_xml': [],
    'installable': True,
    'license': 'AGPL-3',
    'name': u'Kinesis Athletics',
    'test': [],
    'update_xml': [   u'security/kinesis_athletics_group.xml',
                      u'view/evaluation_detail_view.xml',
                      u'view/group_view.xml',
                      u'view/level_view.xml',
                      u'view/company_view.xml',
                      u'view/company_type_view.xml',
                      u'view/test_range_view.xml',
                      u'view/test_category_view.xml',
                      u'view/test_view.xml',
                      u'view/partner_view.xml',
                      u'view/evaluation_view.xml',
                      u'view/test_selection_view.xml',
                      u'view/kinesis_athletics_menuitem.xml',
                      u'data/evaluation_detail_properties.xml',
                      u'data/group_properties.xml',
                      u'data/level_properties.xml',
                      u'data/company_properties.xml',
                      u'data/company_type_properties.xml',
                      u'data/test_range_properties.xml',
                      u'data/test_category_properties.xml',
                      u'data/test_properties.xml',
                      u'data/partner_properties.xml',
                      u'data/evaluation_properties.xml',
                      u'data/test_selection_properties.xml',
                      u'data/evaluation_detail_track.xml',
                      u'data/group_track.xml',
                      u'data/level_track.xml',
                      u'data/company_track.xml',
                      u'data/company_type_track.xml',
                      u'data/test_range_track.xml',
                      u'data/test_category_track.xml',
                      u'data/test_track.xml',
                      u'data/partner_track.xml',
                      u'data/evaluation_track.xml',
                      u'data/test_selection_track.xml',
                      'security/ir.model.access.csv'],
    'version': u'1.7',
    'website': ''}

# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
